### ISSUE TITLE
Add blacklist option for "player" query argument

### ISSUE THREAD

**Issue by yqs112358** [kr8gz/PlayerStatistics#8]
For example, on servers that use carpet mod, those fake player's statistics will contaminate existing data in leaderboard such as "play_time":

![Image](https://github.com/user-attachments/assets/a1a38277-afc1-4fe4-9e91-8449e3bbea3f)

So, I think it world be great if a blacklist option for "player" argument is availble in configuration file, which seems like:
```toml
[query]
player_blacklist = ["playera", "playerb", "bot_*", "*_bot"]
``` 
and it will be applied to each query to filter certain players out of the result.
